<?php

/**
 * @file
 * Kanponents Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function kanponents_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__kan_accordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_accordion_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_card_container' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_columns' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_embed' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_filtered_list' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_hero' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_links_bar' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_media' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_numbered_list_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_numbered_list' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_quicklinks_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_quicklinks' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_text' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__kan_video_modal' => [
      'base hook' => 'paragraph',
    ],
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],
    'field__kan_field_components' => [
      'base hook' => 'paragraph',
    ],
    'field__kan_columns__field_columns__columns' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__kan_field_columns__kan-columns' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function kanponents_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.kanponents':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
